apiVersion: v1
kind: ReplicationController
metadata:
        name: node-apprc
spec:
        replicas: 3
        selector:
         app: node-apprc
        template:
         metadata:
              labels:
                app: node-apprc
         spec:
                containers:
                 - name: node-apprc
                   image: shivampateriyaknoldus/node-js:0.0.1.RELEASE
                   ports:
                     - containerPort: 80

