apiVersion: v1
kind: ReplicationController
metadata:
        name: node-app1
spec:
        replicas: 3
        selector:
                app: node-app1
        template:
                metadata:
                        labels:
                          app: node-app1

                spec:
                        containers:
                                - name: node-app1
                                  image: shivampateriyaknoldus/node-js:0.0.1.RELEASE
                                  ports:
                                          - containerPort: 5000

