apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-rs
  template:
     metadata:
         labels:
           app: node-rs
     spec:
       containers:
       - name: node 
         image: shivampateriyaknoldus/node-js:0.0.1.RELEASE 
