apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:
  completions: 4 #one after another 
  parallelism: 2
  template: #template will be use for creating pod
    spec:
      containers:
         - name: busybox #name of the container 
           image: busybox
           command: ["echo","k8s"]  
      restartPolicy: Never
