apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia 
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate      
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - image: luksa/kubia:v4
          name: node-js


