apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate      
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - image: shivampateriyaknoldus/node-js:0.0.1.RELEASE
          name: node-js


