apiVersion: v1
kind: Service
metadata:
  name: service1  #define the name of the service 
spec:
  ports: 
    - port: 5000 #the port this service will be avaible on
      targetPort: 5000 #the container port the service will forward to
  selector:
    app: test   #all pods with the app= shivam label will be part of this services.


# to list out the service You can simply use kubectl get services.
# by default the type of the services is ClusterIP
