apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ssd-monitor
spec:
  selector:
    matchLabels:
      app: ssd-monitor        
  template:
    metadata:
      labels:
        app: ssd-monitor
    spec:
      # nodeSelector:       #if we dont use node selector it will make pod on every node 
      #   disk: ssd
      containers:
      - name: main
        image: luksa/ssd-monitor

#for more go to example 2       